version: '3'
services:

  tg-stand-for-ukraine:
    build: .
    environment:
      - TOKEN=
      - DB=/app/db/bbolt.db
      - ADMIN=
      - DEBUG=true

      - HUB_APP_ID=
      - HUB_APP_HASH=
      - HUB_PUBLIC_KEY=/app/publicKey.pem
      - HUB_DEVICE=Dmitry Nev
      - HUB_CLIENT_TTL=10m

      - HUB_DC_PORT=443
      - HUB_DC_IP=
      - HUB_DC_ID=2

      - REPORTER_INTERVAL=40m
      - REPORTER_INTERVAL_MAX_REPORTS=25
      - REPORTER_MESSAGE=The channel undermines the integrity of the Ukrainian state. Spreading fake news, misleading people. There are a lot of posts with threats against Ukrainians and Ukrainian soldiers. Block him ASAP
    volumes:
      - ./publicKey.pem:/app/publicKey.pem
      - ./db:/app/db
