version: '3'
services:

  tg-stand-for-ukraine:
    build: .
    environment:
      - TOKEN=
      - DB=/app/db/bbolt.db
      - ADMIN=
      - DEBUG=true
      - HUB_APP_ID=
      - HUB_APP_HASH=
      - HUB_REP_MSG=The channel undermines the integrity of the Ukrainian state. Spreading fake news, misleading people. There are a lot of posts with threats against Ukrainians and Ukrainian soldiers. Block him ASAP
      - HUB_PUBLIC_KEY=/app/publicKey.pem
      - HUB_DEVICE=Dmitry Nev
      - HUB_SEND_REPORTS_INTERVAL=10m
      - HUB_RESEND_REPORT=false
      - HUB_DC_PORT=443
      - HUB_DC_IP=149.154.167.50
      - HUB_DC_ID=2
    volumes:
      - ./publicKey.pem:/app/publicKey.pem
      - ./db:/app/db